import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from './lib/registry';
import Header from './components/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Step into the void",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <>
            {/* <Header /> */}
            {children}
          </>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
